### ISSUE TITLE
Detecting Chrome finds the right version but also finds a null version that crashes browser-launcher2

### ISSUE THREAD

**Issue by dslewis** [vweevers/win-detect-browsers#16]
C:\Windows\System32\WindowsPowerShell\v1.0> win-detect-browsers.cmd

firefox 26.0.0.5087
  @ C:\Program Files (x86)\Mozilla Firefox\firefox.exe

ie 11.0.9600.17416
  @ C:\Program Files (x86)\Internet Explorer\iexplore.exe

ie 11.0.9600.17416
  @ C:\Program Files\Internet Explorer\iexplore.exe

chrome 42.0.2311.90
  @ C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

chrome 
  @ C:\Program Files (x86)\Google\Chrome\Application

**Comment by vweevers** [comment]
Can you please enable debug with `SET DEBUG=win-detect-browsers`, and run win-detect-browsers again? Paste the output in pastebin or a gist, to keep this thread readable. Thanks

**Comment by dslewis** [comment]
Sure thing.
https://gist.github.com/a1a9aa2e921c86b84656.git
I should probably mention that I've seen this on several machines, on with Windows 8.1 x64 and the other two with Windows Server 2012 R2.  Thanks for the prompt follow up.

**Comment by vweevers** [comment]
It appears that the value of one specific registry key on a 64 bit system -`HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe` - is the executable's parent directory, instead of the executable's path. That can be anticipated, should be an easy fix. Additionally I'll add a filter to the results, to only return browsers with a valid path (means an extra fs call, which is why I avoided it before) and a version number.

Thanks for the report.

**Comment by kostasmanionis** [comment]
Having the same issue on Windows 8.1 x64 :( @vweevers any idea when a fix is going to be out?

**Comment by vweevers** [comment]
Postponed because of a severe cold, couple of days I hope

**Comment by vweevers** [comment]
This is fixed in the [2.0 branch](https://github.com/vweevers/win-detect-browsers/tree/2.0). But 2.0 needs to be tested on every Windows edition before I release it. Who wants to help? :)

I'll backport the fix to 1.x tomorrow

**Comment by vweevers** [comment]
Fixed for 1.0 in 20a1a52, released 1.0.2 and 2.0.0.
