### ISSUE TITLE
Does not detect Microsoft Edge

### ISSUE THREAD

**Issue by mitchellsimoens** [vweevers/win-detect-browsers#21]
Trying to detect Microsoft Edge but not having any luck so far editing the `lib/browsers.js`. For me the file is at `C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe/MicrosoftEdge.exe`. Not sure if the `Microsoft.MicrosoftEdge_8wekyb3d8bbwe` is unique or what, looks like it.

Any idea on Edge detection?

**Comment by vweevers** [comment]
I don't have Windows 10 myself, but after a google search, Edge appears to be a typical, lovely, tentacled Microsoft beast. It's not listed in StartMenuEntries, like any other browser. That path you gave is correct. However, that file won't actually launch Edge - so that's useless. Edge cannot be uninstalled, so if the OS is Windows 10 (there are probably ways to detect this), it's safe to assume Edge is installed. That's your best bet.

It can be launched with the `microsoft-edge` protocol, either via start.exe or explorer: `explorer.exe microsoft-edge:[url]`.

But, because win-detect-browsers is expected to output executable paths, and not commands like the above, it cannot currently support Edge.

**Comment by tomitm** [comment]
@vweevers Found something interesting while poking around on #25.

I noticed an `App{...}` key under `HKCR\.html\OpenWithProgIds`, which lead to `HKCR\AppX4hxtad77fbk3jkkeerkrm0ze94wjf3s9` (as expected), which uncovered it was for Edge.

`HKCR\AppX4hxtad77fbk3jkkeerkrm0ze94wjf3s9\shell\open\command` has a (default) value of `"C:\WINDOWS\system32\LaunchWinApp.exe" "%1"` which might be useful here. 

Unfortunately, the `App...' value isn't too useful, but it the value for `HKCR\App...\shell\open\PackageId` can be useful: `Microsoft.MicrosoftEdge_34.14291.1001.0_neutral__8wekyb3d8bbwe`

This eventually leads me to `HKCRLocal Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\Microsoft.MicrosoftEdge_34.14291.1001.0_neutral__8wekyb3d8bbwe` which has a single `Path` key with value `C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe`

That path has a `MicrosoftEdge.exe` and `MicrosftEdgeCP.exe`, neither of which seem to launch Edge. Not sure how `LaunchWinApp.exe` is relevant either.

Eventually came across [this answer](http://stackoverflow.com/a/34798628) saying it's not yet supported. Also, they seem to have created a [MicrosoftEdgeLauncher](https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher) project. Must be a WIP before they integrate it into Edge.

**Comment by vweevers** [comment]
Thanks @tomitm. Yes, detecting Edge is relatively easy, but I arrived at the same conclusion. And without an executable you can't safely kill it, specify parameters, profiles, etc.. MicrosoftEdgeLauncher doesn't do anything more than `start microsoft-edge:url` btw, it's ridiculous.

**Comment by vweevers** [comment]
Anyone looking to launch Edge, please see https://github.com/eugeneware/windows-edge.
